# Generated by Django 3.0.3 on 2020-03-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'default_related_name': 'articlescopes', 'ordering': ['-is_main'], 'verbose_name': 'СтатьяРаздел', 'verbose_name_plural': 'СтатьиРазделы'},
        ),
        migrations.RenameField(
            model_name='articlescope',
            old_name='main',
            new_name='is_main',
        ),
    ]
